require('./base');
require('./nav');
// require('./article');
require('./components/article');
require('./components/asset');
require('./components/cart');
require('./components/library');
require('./components/noti');
require('./components/transaction');
require('./components/user');
// require('./views/mirui-auth');
// require('./views/mirui-auth-login');
// require('./views/mirui-auth-register');
require('./views/mirui-dashboard');
require('./views/mirui-dashboard-article');
require('./views/mirui-dashboard-cart');
require('./views/mirui-dashboard-library');
require('./views/mirui-dashboard-risk');
require('./views/mirui-dashboard-transaction');
require('./views/mirui-dashboard-user');